### PR TITLE
Fixes for tls, grafana variable syntax, victoriametrics and the check_nwc_health-interface.php template

### PR DESCRIPTION
**Pull request by jstark1**
This patch skips TLS checks to the database, to prevent this error:

histou_victoriametrics_ssl_error

### CODE REVIEW

**Comment by jstark1** [comment]
The patches should fix https://github.com/ConSol-Monitoring/omd/issues/206

**Comment by sni** [comment]
could you explain your changes a little bit?

**Comment by jstark1** [comment]
Sure, 
1. PHP default checks the TLS Certificates. If we use InfluxDB or Victoriametrics in SSL mode, Histou fails with the TLS error above. One option is to use valid Certificates and correct Hostnames/IPs and give PHP and Grafana a truststore to check the validity. In my Change, we simply bypass the certificate checks, like the Grafana datasources. 
2. If we use Grafana dashboards with dynamic variables, like the check_nwc_health-interface.php template, we need to bypass the default Grafana template quoting, to use values correct values in the graph lookups with the new template ${var:raw}
3. The InfluxDB Dashboard works now, in the third commit I checked the same check_nwc_health-interface.php dashboard with Victoriametrics. I don't know if and how it worked before, so I replaced the label lookup (https://docs.victoriametrics.com/url-examples/#apiv1labels)
4. The last 3 commits are GUI polish and a logic error in the check_nwc_health-interface.php template

The Pull Request https://github.com/sni/Thruk/pull/1404 are also on the GUI side the hide the new grafana variable syntax 

I hop this helps

**Comment by sni** [comment]
maybe separate pull request would have been better.
I agree with the label lookup and the template syntax.
The changes to the nwc template are probably personal preferences. So i would leave them out.
The ssl verfication should be at least optional and enabled by default. What's the reason to
enable ssl but then disable verification?

**Comment by sni** [comment]
i cherry-picked those commits for now.

**Comment by jstark1** [comment]
Sure, TLS is always a hot topic. I agree when we say: The OMD options INFLUXDB_MODE: ssl and VICTORIAMETRICS_MODE: ssl should only be used with targets with valid certificates that are verifiable through the system trust store.

To the nwc template [1ce08d8](https://github.com/ConSol-Monitoring/histou/pull/4/commits/1ce08d86a68885ec288567ec5acd96f5bc92cca4) can be discussed, but https://github.com/ConSol-Monitoring/histou/pull/4/commits/56550c5f048aff89e87b394a467dad5183346111 and https://github.com/ConSol-Monitoring/histou/pull/4/commits/76695362aed709f63e71e7fef7b5af61c0a3590e are errors in my option

**Comment by sni** [comment]
agreed, cherry-picked those 2 as well

**Comment by jstark1** [comment]
thanks

**Pull request closed without merging**
